# Generated by Django 2.0 on 2018-06-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image_added',
            field=models.CharField(choices=[(0, 'NotAdded'), (1, 'Added')], default=0, max_length=3),
        ),
    ]
