# Generated by Django 2.0 on 2018-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180621_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiverview',
            field=models.CharField(default='View', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='senderview',
            field=models.CharField(default='View', max_length=20),
        ),
    ]
