# Generated by Django 2.0 on 2018-06-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180623_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiverview',
        ),
        migrations.RemoveField(
            model_name='message',
            name='senderview',
        ),
    ]
