# Generated by Django 2.0 on 2018-07-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='user',
        ),
        migrations.DeleteModel(
            name='Online',
        ),
    ]
