# Generated by Django 2.0.6 on 2018-07-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_cover_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_pic',
        ),
    ]
